name: LaTeX CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: xu-cheng/latex-action@v2
      with:
        root_file: thesis/tesi.tex
        latexmk_flavor: latexmk

    - name: Compile LaTeX document
      run: latexmk -pdf -cd thesis/tesi.tex
