name: latex rough_notes

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    paths:
    - 'thesis/tesi.tex'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  latex-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: download paper repo
        uses: actions/checkout@v1
      - name: build pdf 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tesi.tex
          working_directory: thesis