name: Compile LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: dante-ev/latex-action@v2

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -f thesis.tex
      env:
        # Set the default environment variables here if needed
        # PATH: /path/to/texlive/bin:$PATH

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: your_document.pdf
